services:
  bookify.api:
    image: bookify.api
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:80"
#      - "5001:443"
    depends_on:
      - bookify-db
  
  bookify-db:
    image: postgres:alpine
    container_name: Bookify.Db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/volumes/bookify-db:/var/lib/postgresql/data