# This is a generated file. Not intended for manual editing.
services:
  bookify.api:
    build:
      context: "/Users/xobbit_26/Projects/Bookify"
      dockerfile: "Bookify.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Bookify.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookify.api:dev"
    ports: []
    volumes:
    - "/Users/xobbit_26/Projects/Bookify/Bookify.Api:/app:rw"
    - "/Users/xobbit_26/Projects/Bookify:/src:rw"
    - "/Users/xobbit_26/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
