# This is a generated file. Not intended for manual editing.
services:
  bookify.api:
    build:
      context: "/Users/xobbit_26/Projects/Bookify"
      dockerfile: "Bookify.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "bookify.api:dev"
    ports:
    - "127.0.0.1:57010:57000"
    - "127.0.0.1:57210:57200"
    - "127.0.0.1:57410:57400"
    volumes:
    - "/Users/xobbit_26/Projects/Bookify/Bookify.Api:/app:rw"
    - "/Users/xobbit_26/Projects/Bookify:/src:rw"
    - "/Users/xobbit_26/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/xobbit_26/.local/share/JetBrains/RiderRemoteDebugger/2024.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/xobbit_26/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/xobbit_26/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_11_23_18_56_07:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
